1
SELECT T.TASK_ID, TASK_DESC, TASK_STARTDATE, TASK_ENDDATE, SKILL_DESC, EMP_LNAME, EMP_FNAME, ASSIGN_STARTDATE, ASSIGN_ENDDATE
FROM TASKSKILL TS JOIN SKILL S ON TS.SKILL_ID = S.SKILL_ID JOIN TASK T ON TS.TASK_ID=T.TASK_ID JOIN ASSIGNMENT A ON TS.TASKSKILL_ID=A.TASKSKILL_ID JOIN EMPLOYEE E ON E.EMP_ID = A. EMP_ID
ORDER BY TASK_STARTDATE, TASK_ENDDATE;
/*--*/

2
SELECT T.TASK_ID, TASK_STARTDATE, TASK_ENDDATE, TASK_DESC, SKILL_DESC, TASKSKILL_QTY
FROM TASKSKILL TS JOIN SKILL S ON TS.SKILL_ID = S.SKILL_ID JOIN TASK T ON TS.TASK_ID=T.TASK_ID
ORDER BY TASK_STARTDATE, TASK_ENDDATE;
/*--*/

3
SELECT REGION_NAME, SKILL_DESC, EMP_LNAME, EMP_FNAME, EMP_HIREDATE
FROM REGION R JOIN EMPLOYEE E ON R.REGION_ID=E.REGION_ID JOIN EMPSKILL ES ON ES.EMP_ID=E.EMP_ID JOIN SKILL S ON S.SKILL_ID=ES.SKILL_ID
WHERE REGION_NAME <> 'MN'
ORDER BY REGION_NAME, SKILL_DESC, EMP_HIREDATE;
/*--*/

4
SELECT TASK_DESC, SKILL_DESC, EMP_LNAME, EMP_FNAME
FROM TASK T JOIN TASKSKILL TS ON TS.TASK_ID=T.TASK_ID JOIN SKILL S ON TS.SKILL_ID = S.SKILL_ID JOIN EMPSKILL ES ON ES.SKILL_ID= S.SKILL_ID JOIN EMPLOYEE E ON E.EMP_ID=ES.EMP_ID
WHERE TASK_STARTDATE>= '2018-06-10'
ORDER BY TASK_STARTDATE
/*--*/

5
SELECT REGION_NAME, SKILL_DESC, EMP_LNAME, EMP_FNAME
FROM REGION R JOIN EMPLOYEE E ON R.REGION_ID=E.REGION_ID JOIN EMPSKILL ES ON ES.EMP_ID=E.EMP_ID JOIN SKILL S ON S.SKILL_ID=ES.SKILL_ID
ORDER BY REGION_NAME, SKILL_DESC;
/*--*/

6
SELECT SKILL_DESC, SUM(WORKLOG_HOURS), SKILL_RATE, ROUND(SUM(SKILL_RATE * WORKLOG_HOURS), 2) AS 'TOTAL'
FROM SKILL S JOIN TASKSKILL TS ON S.SKILL_ID=TS.SKILL_ID JOIN ASSIGNMENT A ON A.TASKSKILL_ID=TS.TASKSKILL_ID JOIN WORKLOG W ON W.ASSIGN_ID=A.ASSIGN_ID 
WHERE SKILL_DESC <> 'JAVA I' AND SKILL_DESC <> 'JAVA II'
    AND  SKILL_DESC<> 'TECHNICAL WRITER' AND BILL_ID= '100' 
GROUP BY  SKILL_DESC, SKILL_RATE
ORDER BY SKILL_DESC;
/*--*/

7
SELECT PROJ_DESC, SUM(WORKLOG_HOURS) AS 'TOTAL HOURS', ROUND(SUM(SKILL_RATE * WORKLOG_HOURS), 0) AS 'TOTAL BILLED'
FROM PROJECT P JOIN BILL B ON P.PROJ_ID=B.PROJ_ID JOIN WORKLOG W ON W.BILL_ID=B.BILL_ID JOIN ASSIGNMENT A ON A.ASSIGN_ID=W.ASSIGN_ID JOIN TASKSKILL TS ON A.TASKSKILL_ID=TS.TASKSKILL_ID JOIN SKILL S ON S.SKILL_ID=TS.SKILL_ID 
GROUP BY PROJ_DESC
/*--*/

8
SELECT EMP_LNAME, EMP_FNAME, SKILL_DESC, SKILL_RATE, SUM(WORKLOG_HOURS) AS 'TOTAL HOURS', ROUND(SUM(SKILL_RATE * WORKLOG_HOURS), 2) AS 'TOTAL'
FROM SKILL S JOIN EMPSKILL ES ON S.SKILL_ID=ES.SKILL_ID JOIN EMPLOYEE E ON ES.EMP_ID=E.EMP_ID JOIN ASSIGNMENT A ON A.EMP_ID=E.EMP_ID JOIN WORKLOG W ON W.ASSIGN_ID=A.ASSIGN_ID
GROUP BY EMP_LNAME, EMP_FNAME, SKILL_DESC, SKILL_RATE
ORDER BY EMP_LNAME, EMP_FNAME, SKILL_DESC, SKILL_RATE;
/*--*/

9
SELECT S.SKILL_ID, SKILL_DESC, EMP_LNAME, EMP_FNAME
FROM EMPLOYEE E JOIN EMPSKILL ES ON E.EMP_ID=ES.EMP_ID JOIN SKILL S ON ES.SKILL_ID=S.SKILL_ID
ORDER BY S.SKILL_ID, EMP_LNAME;
/*--*/

10
SELECT EMP_LNAME, EMP_FNAME, WORKLOG_DATE, A.ASSIGN_ID, TASK_DESC, SKILL_DESC, WORKLOG_HOURS, B.BILL_ID
FROM EMPLOYEE E JOIN ASSIGNMENT A ON E.EMP_ID=A.EMP_ID JOIN WORKLOG W ON W.ASSIGN_ID=A.ASSIGN_ID JOIN BILL B ON B.BILL_ID=W.BILL_ID JOIN PROJECT P ON P.PROJ_ID=B.PROJ_ID JOIN TASK T ON T.PROJ_ID=P.PROJ_ID
JOIN TASKSKILL TS ON T.TASK_ID=TS.TASK_ID JOIN SKILL S ON TS.SKILL_ID = S.SKILL_ID 
ORDER BY ASSIGN_ID, WORKLOG_DATE, WORKLOG_HOURS, TASK_DESC, EMP_LNAME, EMP_FNAME;
/*--*/

11
SELECT EMP_LNAME, EMP_FNAME, TASK_DESC, SKILL_DESC, SUM(WORKLOG_HOURS) AS 'Sum Of Worklog Hours', SKILL_RATE, ROUND(SUM(WORKLOG_HOURS *SKILL_RATE), 2) 'TOTAL'
FROM EMPLOYEE E JOIN ASSIGNMENT A ON E.EMP_ID=A.EMP_ID JOIN WORKLOG W ON W.ASSIGN_ID=A.ASSIGN_ID JOIN BILL B ON B.BILL_ID=W.BILL_ID JOIN PROJECT P ON P.PROJ_ID=B.PROJ_ID JOIN TASK T ON T.PROJ_ID=P.PROJ_ID
JOIN TASKSKILL TS ON T.TASK_ID=TS.TASK_ID JOIN SKILL S ON TS.SKILL_ID = S.SKILL_ID 
GROUP BY EMP_LNAME, EMP_FNAME,TASK_DESC,SKILL_DESC,SKILL_RATE, A.ASSIGN_ID
ORDER BY A.ASSIGN_ID;
/*--*/